# Default application configuration that all configurations inherit from.

linters:
  EmptyLineBetweenBlocks:
    enabled: false

  ImportantRule:
    exclude:
      - "assets/stylesheets/lib/columns/**"
      - "assets/stylesheets/lib/overriders/**"
      - "assets/stylesheets/lib/mixins/**"
      - "assets/stylesheets/lib/global/_tables.scss"

  NestingDepth:
    enabled: false

  SelectorDepth:
    enabled: false

  SpaceBeforeBrace:
    enabled: true
    style: space
    allow_single_line_padding: true

  StringQuotes:
    enabled: true
    style: double_quotes
